apiVersion: v1
kind: Service
metadata:
  name: my-python-github-cicd-app-service
spec:
  selector:
    app: my-python-github-cicd-app           # Service 使用此标签选择其 Pod
  ports:
    - protocol: TCP
      port: 80           # 集群内部访问的端口
      targetPort: 5000     # 容器内部的端口
      nodePort: 30005    # 外部访问的端口，选择一个30000-32767范围内的端口
  type: NodePort
